### ISSUE TITLE
creates the Folders, deletes the video, but no Pics created

### ISSUE THREAD

**Issue by hank-arus** [MotorCityCobra/face_ripper#1]
I replaced the paths:

                        if not os.path.exists('./output/vidpics' + str(count) + '/'):
                                os.makedirs('./output/vidpics' + str(count) + '/')

                        vid = random.choice(glob.glob('./input/'+'*.mp4'))

                        name = ('./output/vidpics' + str(count) + '/' + str(uuid.uuid4()) + '.jpg')

Then I run:

python3 1_vids_to_pics.py

It runs and creates the folders without an error message

python3 1_vids_to_pics.py 
Creating..../output/vidpics1/8318707c-c2fe-4380-b005-b181d98bb236.jpg

But after a second, it stops and the video is gone. Not even this .jpg is present.

I tried different .mp4, all the same. Am I missing something?

**Comment by MotorCityCobra** [comment]
Have you tried specifying to the full output path name?  
Not just ('./output/vidpics' + str(count) + '/')  
But the FULL path like ('C:/Computer/User/Windows/Output/vidpics' + str(count) + '/')?

In my experience the terminal window will say a file is being written to a path, but actually create no files when the path doesn't exist. In this case, hasn't been created.  

Have you tried getting it to output the jpgs to a path you are 100% sure about the location and path name of?

**Comment by hank-arus** [comment]
I used absolute Paths and now it works, tried again with ./ and it worked, too.

I figured out that the reason was that I changed the opencv Version from 3.3.0 to 3.4 (faceswap installed 3.3). That solved a problem with another face-extraction tool, too.

So the solution is:

pip3 uninstall opencv-python
pip3 uninstall opencv-python

So it was my mistake, sorry! Thanks for your help!

**Comment by MotorCityCobra** [comment]
Good.
I know the dependencies can be very difficult to get up and running. I still can't get dlib to use my GPU.
I refer the dependency installation to the face_recognition repo. Same dependencies needed here but his repo has lots of open and closed issues that arised when installing the depandies.
